# Generated by Django 5.1.4 on 2025-01-26 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="youtube_url",
            field=models.URLField(null=True),
        ),
    ]
