# Generated by Django 5.1.4 on 2025-01-26 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_author_bio_author_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="image",
        ),
    ]
