# Generated by Django 5.1.4 on 2025-01-28 04:39

import blog.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_faq"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="author",
            options={"verbose_name": "Autor", "verbose_name_plural": "Autores"},
        ),
        migrations.AlterModelOptions(
            name="comment",
            options={
                "verbose_name": "Comentario",
                "verbose_name_plural": "Comentarios",
            },
        ),
        migrations.AlterModelOptions(
            name="faq",
            options={
                "verbose_name": "Pregunta frecuente",
                "verbose_name_plural": "Preguntas frecuentes",
            },
        ),
        migrations.AlterModelOptions(
            name="post",
            options={"verbose_name": "Video", "verbose_name_plural": "Videos"},
        ),
        migrations.AlterModelOptions(
            name="tag",
            options={"verbose_name": "Etiqueta", "verbose_name_plural": "Etiquetas"},
        ),
        migrations.AlterField(
            model_name="author",
            name="bio",
            field=models.TextField(
                null=True,
                validators=[django.core.validators.MinLengthValidator(10)],
                verbose_name="biografía",
            ),
        ),
        migrations.AlterField(
            model_name="author",
            name="email_address",
            field=models.EmailField(max_length=254, verbose_name="correo electrónico"),
        ),
        migrations.AlterField(
            model_name="author",
            name="first_name",
            field=models.CharField(max_length=100, verbose_name="nombre"),
        ),
        migrations.AlterField(
            model_name="author",
            name="image",
            field=models.ImageField(
                null=True,
                upload_to="authors",
                validators=[blog.models.validate_image_size],
                verbose_name="imagen",
            ),
        ),
        migrations.AlterField(
            model_name="author",
            name="last_name",
            field=models.CharField(max_length=100, verbose_name="apellido"),
        ),
        migrations.AlterField(
            model_name="comment",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="blog.post",
                verbose_name="video",
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="text",
            field=models.TextField(max_length=400, verbose_name="comentario"),
        ),
        migrations.AlterField(
            model_name="comment",
            name="user_email",
            field=models.EmailField(max_length=254, verbose_name="correo electrónico"),
        ),
        migrations.AlterField(
            model_name="comment",
            name="user_name",
            field=models.CharField(max_length=100, verbose_name="nombre de usuario"),
        ),
        migrations.AlterField(
            model_name="faq",
            name="answer",
            field=models.TextField(max_length=400, verbose_name="respuesta"),
        ),
        migrations.AlterField(
            model_name="faq",
            name="question",
            field=models.CharField(max_length=100, verbose_name="pregunta"),
        ),
        migrations.AlterField(
            model_name="post",
            name="author",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="posts",
                to="blog.author",
                verbose_name="autor",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="content",
            field=models.TextField(
                validators=[django.core.validators.MinLengthValidator(10)],
                verbose_name="contenido",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="date",
            field=models.DateField(auto_now=True, verbose_name="fecha"),
        ),
        migrations.AlterField(
            model_name="post",
            name="excerpt",
            field=models.CharField(max_length=200, null=True, verbose_name="resumen"),
        ),
        migrations.AlterField(
            model_name="post",
            name="slug",
            field=models.SlugField(unique=True, verbose_name="slug"),
        ),
        migrations.AlterField(
            model_name="post",
            name="tags",
            field=models.ManyToManyField(
                related_name="posts", to="blog.tag", verbose_name="etiquetas"
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="title",
            field=models.CharField(max_length=150, verbose_name="título"),
        ),
        migrations.AlterField(
            model_name="post",
            name="youtube_url",
            field=models.URLField(null=True, verbose_name="URL de YouTube"),
        ),
        migrations.AlterField(
            model_name="tag",
            name="caption",
            field=models.CharField(max_length=20, verbose_name="etiqueta"),
        ),
    ]
