# Generated by Django 5.1.4 on 2025-01-28 19:53

import blog.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0006_alter_author_options_alter_comment_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Carousel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="Título")),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        max_length=400,
                        null=True,
                        verbose_name="Descripción",
                    ),
                ),
            ],
            options={
                "verbose_name": "Carrusel",
                "verbose_name_plural": "Carruseles",
            },
        ),
        migrations.CreateModel(
            name="CarouselImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="carousel/images",
                        validators=[blog.models.validate_image_size],
                        verbose_name="Imagen",
                    ),
                ),
                (
                    "caption",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Pie de foto",
                    ),
                ),
                ("url", models.URLField(blank=True, null=True, verbose_name="URL")),
                (
                    "carousel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="blog.carousel",
                        verbose_name="Carrusel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Imagen del Carrusel",
                "verbose_name_plural": "Imágenes del Carrusel",
            },
        ),
    ]
